<?php

namespace App\Views;

use App\app;
use Core\View;

class Navigation extends View
{

    public function __construct()
    {
        parent::__construct($this->generate());
    }

    public function generate()
    {

        if (App::$session->getUser()) {
            return [
                App::$router::getUrl('index') => 'Home',
                App::$router::getUrl('add') => 'Add',
                App::$router::getUrl('list') => 'Edit',
                App::$router::getUrl('logout') => 'Logout',
            ];
        } else {
            return [
                App::$router::getUrl('index') => 'Home',
                App::$router::getUrl('register') => 'Register',
                App::$router::getUrl('login') => 'Login',
            ];
        }
//        if (App::$session->getUser()){
//            return [
//                'links' => [
//                    'home' => [
//                        'value' => 'Home',
//                        'path' => '/index.php'
//                    ],
//                    'add' => [
//                        'value' => 'Add Item',
//                        'path' => '/admin/add.php'
//                    ],
//                    'mypoo' => [
//                        'value' => 'My Poo',
//                        'path' => '/admin/list.php'
//                    ],
//                    'logout' => [
//                        'value' => 'Log Out',
//                        'path' => '/logout.php'
//                    ],
//
//                ],
//            ];
//        } else {
//            return [
//                'links' => [
//                    'home' => [
//                        'value' => 'Home',
//                        'path' => '/index.php'
//                    ],
//                    'register' => [
//                        'value' => 'Register',
//                        'path' => '/register.php'
//                    ],
//                    'login' => [
//                        'value' => 'Log In',
//                        'path' => '/login.php'
//                    ]
//                ],
//            ];
//        }
    }

    public function render($template_path = ROOT . '/app/templates/nav.tpl.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }
}